<!DOCTYPE html><html lang="ko" prefix="og: http://ogp.me/ns#"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><title>unittest와 함께하는 파이썬 테스트 · 안녕 프로그래밍</title><meta name="description" content="파이썬 TDD로 시작하기"><meta name="og:title" content="unittest와 함께하는 파이썬 테스트"><meta name="og:type" content="website"><meta name="og:url" content="https://www.holaxprogramming.com/2017/06/17/python-with-test/"><meta name="og:image" content="http://image.toast.com/aaaaahq/hola_cover.JPG"><meta name="og:description" content="파이썬 TDD로 시작하기"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/css/chiangmai.css"><meta name="steem:author" content="@stunstunstun"><meta name="fb:app_id" content="1258629384258634"><link rel="search" type="application/opensearchdescription+xml" href="https://www.holaxprogramming.com/atom.xml" title="안녕 프로그래밍"></head><body class="post"><div id="fb-root"></div><div class="wrap"><header><nav class="navi-post"><a class="navi-post-back" href="javascript:history.back()"><i class="fa fa-arrow-left" aria-hidden="true"></i></a><a class="navi-post-home" href="/"><i class="fa fa-home" aria-hidden="true"></i></a></nav></header><main class="post"><div class="post"><article class="post-block"><h1 class="post-title">unittest와 함께하는 파이썬 테스트</h1><div class="post-info"><div class="post-info-profile"><a href="https://github.com/stunstunstun" target="_blank"><img src="/image/profile.jpg"></a></div><div class="post-info-details"><div class="post-categories"><a href="/categories/python" target="_self"><span>PYTHON</span></a></div><div class="post-date">2017년 6월 17일</div></div></div><div class="post-share"><div class="fb-like" data-href="https://www.holaxprogramming.com/2017/06/17/python-with-test/" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="false">                 </div><div class="fb-share-button" data-href="https://www.holaxprogramming.com/2017/06/17/python-with-test/" data-layout="button" data-size="small" data-mobile-iframe="true"></div><div class="fb-follow" data-href="https://www.facebook.com/holaxprogramming/" data-layout="button_count" data-size="small" data-show-faces="true"></div></div><div class="post-content"><p><a href="https://www.holaxprogramming.com/2017/06/15/python-get-started/">지난 글</a>에서는 TDD와 함께 파이썬의 개발 환경을 준비하고 첫 테스트 케이스를 작성하였다. 테스트 코드를 먼저 작성함으로써 다양한 문제에 자연스럽게 노출될 수 있었는데 여전히 테스트를 실행하기 위한 의문을 남겨놓은 상태이다. 의문을 풀기 위해 테스트를 위한 표준 라이브러리인 <code>unittest</code>에 대해 자세히 살펴볼 필요가 있다. Google의 검색창에서 아래의 키워드를 통해 검색해본다. </p>
<a id="more"></a>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">python unittest</span><br></pre></td></tr></table></figure>
<p>검색한 결과에서 가장 상위에 노출되고 있는 <a href="https://docs.python.org/3/library/unittest.html" target="_blank" rel="external"><code>26.4. unittest — Unit testing framework — Python 3.6.1 documentation</code></a>를 참고하기로 했다. 문서에 의하면 테스트를 실행하기 위한 클래스는 <code>unittest</code> 패키지의 <code>TestCase</code> 클래스를 상속받는다. 자 그럼 다시 테스트 클래스를 살펴볼 차례다.</p>
<p><code>test_array.py</code><br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">import unittest</span><br><span class="line">from algorithms import array</span><br><span class="line"></span><br><span class="line">class TestArray(unittest.TestCase):</span><br><span class="line">    &quot;&quot;&quot;</span><br><span class="line">    Test that the result sum of all numbers</span><br><span class="line">    &quot;&quot;&quot;</span><br><span class="line">    def test_sum(self):</span><br><span class="line">        instance = array.Array()</span><br><span class="line">        result = instance.sum(6, &apos;1 2 3 4 10 11&apos;)</span><br><span class="line">        self.assertEqual(result, 31)</span><br></pre></td></tr></table></figure></p>
<p>TestCase 클래스를 상속받아 구현하였으며 구현 클래스의 첫 테스트 케이스를 검증하기 위한 <code>test_sum</code> Function을 가지고 있다. 테스트 코드를 실행하기 위한 커맨드 라인 명령은 아래와 같다.</p>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">$ python -m unittest</span><br></pre></td></tr></table></figure>
<p>실행해야 할 테스트가 많다면 위와 같이 모든 테스트를 실행할 수도 있으며 아래와 같이 특정 Test Case만 실행할 수도 있다.</p>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">$ python -m unittest tests/test_array.py</span><br></pre></td></tr></table></figure>
<p>자 그럼 테스트를 실행해볼 차례다!</p>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">FF</span><br><span class="line">======================================================================</span><br><span class="line">FAIL: test_sum (tests.test_array.TestArray)</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/Users/jungminhyuck/github/awesome-algorithms/tests/test_array.py"</span>, line 10, <span class="keyword">in</span> test_sum</span><br><span class="line">    self.assertEqual(result, 31)</span><br><span class="line">AssertionError: 0 != 31</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran 1 tests <span class="keyword">in</span> 0.005s</span><br><span class="line"></span><br><span class="line">FAILED (failures=1)</span><br></pre></td></tr></table></figure>
<p>테스트가 역시 실패하였다(..) 하지만 긍정적인 점은 앞으로 <code>sum</code> Function을 검증하기 위해 프로그램 내부에서 직접 확인할 필요도 없으며 위와 같이 테스트를 실행하는 것만으로 <code>실패한 원인과 위치</code>를 쉽게 알 수 있게 되었다. 이제는 구현 클래스로 돌아가 볼 차례다.</p>
<p><code>array.py</code></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Array</span><span class="params">(object)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">sum</span><span class="params">(self, size, array_string)</span>:</span></span><br><span class="line">        <span class="keyword">return</span> <span class="number">0</span></span><br></pre></td></tr></table></figure>
<p>Array 클래스의 <code>sum</code>은 아무 일도 하지 않고 <code>0</code>을 반환하기 때문에 우리가 기대하는 대로 동작하지 않고 있다. Function을 아래와 같이 수정한 뒤 다시 테스트해 보았다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Array</span><span class="params">(object)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">sum</span><span class="params">(self, size, array_string)</span>:</span></span><br><span class="line">        numbers = [int(number) <span class="keyword">for</span> number <span class="keyword">in</span> array_string.split(<span class="string">' '</span>)]</span><br><span class="line">        <span class="keyword">return</span> sum(numbers)</span><br></pre></td></tr></table></figure>
<figure class="highlight bash"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">$ python -m unittest</span><br><span class="line">..</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran 1 tests <span class="keyword">in</span> 0.000s</span><br><span class="line"></span><br><span class="line">OK</span><br></pre></td></tr></table></figure>
<p>드디어 테스트가 성공하였다! PyCharm을 사용한다면 처음으로 초록 막대기를 보게 되는 행복한 일도 생겼다. 이제 다시 Array 클래스의 요구사항을 살펴볼 차례다.</p>
<ul>
<li>[x] 첫 번째 Argument는 덧셈에 필요한 숫자의 개수를 전달한다.</li>
<li>[x] 두 번째 Argument는 덧셈에 필요한 숫자를 공백을 포함한 문자열의 형태로 전달한다.</li>
<li>[x] 두 번째 Argument로 전달된 숫자들의 합을 반환한다.</li>
<li>[ ] 첫 번째 Argument의 숫자와 두 번째 Argument의 숫자의 개수가 같은지 체크하고 틀리다면 예외를 발생시킨다.</li>
</ul>
<p>우리는 지금까지 많은 문제들을 해결하였지만 현재의 테스트 케이스로는 마지막 문제를 검증할 수 없는 상태이다. </p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">첫 번째 Argument의 숫자와 두 번째 Argument의 숫자의 개수가 같은지 체크하고 틀리다면 예외를 발생시킨다.</span><br></pre></td></tr></table></figure>
<p>즉 아래와 같이 첫 번째 인자의 값과 두 번째 인자의 문자열에 포함되는 숫자들의 개수가 다르면 <code>sum</code>에서는 예외를 발생시켜야 된다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">instance = array.Array()</span><br><span class="line">instance.sum(<span class="number">5</span>, <span class="string">'1 2 3 4 10 11'</span>)</span><br></pre></td></tr></table></figure>
<p>앞서 미리 살펴본 <code>unittest</code>의 <a href="https://docs.python.org/3/library/unittest.html" target="_blank" rel="external">문서</a>를 통해 TestCase 클래스에서는 <code>assertRaises</code>와 파이썬의 람다식을 통해 아래와 같이 예외가 발생하는지에 대한 여부를 검증할 수가 있었다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">TestArray</span><span class="params">(unittest.TestCase)</span>:</span></span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Tests that an exception occurs when the number of arguments is different</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">test_sum_raise_exception</span><span class="params">(self)</span>:</span></span><br><span class="line">        self.assertRaises(Exception, <span class="keyword">lambda</span>: array.Array().sum(<span class="number">5</span>, <span class="string">'1 2 3 4 10 11'</span>))</span><br></pre></td></tr></table></figure>
<p>테스트 코드를 작성하였으니 주저 말고 테스트를 실행해보자.</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line">$ python -m unittest</span><br><span class="line">.F</span><br><span class="line">======================================================================</span><br><span class="line">FAIL: test_sum_raise_exception (tests.test_array.TestArray)</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;/Users/jungminhyuck/github/awesome-algorithms/tests/test_array.py&quot;, line 19, in test_sum_raise_exception</span><br><span class="line">    self.assertRaises(Exception, lambda: array.Array().sum(5, &apos;1 2 3 4 10 11&apos;))</span><br><span class="line">AssertionError: Exception not raised by &lt;lambda&gt;</span><br><span class="line"></span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran 2 tests in 0.003s</span><br><span class="line"></span><br><span class="line">FAILED (failures=1)</span><br></pre></td></tr></table></figure>
<p>기존의 <code>test_sum</code>에서는 테스트가 성공하였지만 마지막 문제를 검증하기 위한 <code>test_sum_raise_exception</code>에서는 테스트가 실패한 것을 볼 수 있다. 이대로라면 <code>sum</code> Function은 올바르지 않은 Argument가 전달되어도 정상으로 작동되는 무서운 결과를 초래할 수 있어 보인다.</p>
<p>파이썬에서 예외를 발생하기 위한 방법은 무엇일까? 이번에는 검색 결과로 얻은 <a href="https://docs.python.org/3/tutorial/errors.html" target="_blank" rel="external"><code>8. Errors and Exceptions — Python 3.6.1 documentation</code></a>이라는 문서를 참고해 보았다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Array</span><span class="params">(object)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">sum</span><span class="params">(self, size, array_string)</span>:</span></span><br><span class="line">        numbers = [int(number) <span class="keyword">for</span> number <span class="keyword">in</span> array_string.split(<span class="string">' '</span>)]</span><br><span class="line">        <span class="keyword">if</span> size != len(numbers):</span><br><span class="line">            <span class="keyword">raise</span> Exception(<span class="string">'array size is not matched'</span>)</span><br><span class="line">        <span class="keyword">return</span> sum(numbers)</span><br></pre></td></tr></table></figure>
<p>위와 같이 예외를 발생시키기 위해 파이썬의 <code>raise</code> 키워드와 Built-in 클래스인 <code>Exception</code>을 통해서 <code>sum</code>의 첫 번째 인자의 값과 두 번째 인자의 문자열에 포함되는 숫자들의 개수가 다르면 예외를 발생시키는 모습이다. 다시 테스트해보자!</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">$ python -m unittest </span><br><span class="line">..</span><br><span class="line">----------------------------------------------------------------------</span><br><span class="line">Ran 2 tests in 0.001s</span><br><span class="line"></span><br><span class="line">OK</span><br></pre></td></tr></table></figure>
<p><br></p>
<p>테스트가 성공한 행복한 일이 벌어졌으니 이 쯤에서 TestCase 클래스를 자세히 살펴봐도 좋아 보인다. 먼저 TestCase 클래스에서 제공하는 assert Functions의 리스트는 아래와 같다.</p>
<table>
<thead>
<tr>
<th>Method</th>
<th>Checks that</th>
<th>New in</th>
</tr>
</thead>
<tbody>
<tr>
<td>assertEqual(a, b)</td>
<td>a == b</td>
<td></td>
</tr>
<tr>
<td>assertNotEqual(a, b)</td>
<td>a != b</td>
<td></td>
</tr>
<tr>
<td>assertTrue(x)</td>
<td>bool(x) is True</td>
<td></td>
</tr>
<tr>
<td>assertFalse(x)</td>
<td>bool(x) is False</td>
<td></td>
</tr>
<tr>
<td>assertIs(a, b)</td>
<td>a is b</td>
<td>3.1</td>
</tr>
<tr>
<td>assertIsNot(a, b)</td>
<td>a is not b</td>
<td>3.1</td>
</tr>
<tr>
<td>assertIsNone(x)</td>
<td>x is None</td>
<td>3.1</td>
</tr>
<tr>
<td>assertIsNotNone(x)</td>
<td>x is not None</td>
<td>3.1</td>
</tr>
<tr>
<td>assertIn(a, b)</td>
<td>a in b</td>
<td>3.1</td>
</tr>
<tr>
<td>assertNotIn(a, b)</td>
<td>a not in b</td>
<td>3.1</td>
</tr>
<tr>
<td>assertIsInstance(a, b)</td>
<td>isinstance(a, b)</td>
<td>3.2</td>
</tr>
<tr>
<td>assertNotIsInstance(a, b)</td>
<td>not isinstance(a, b)</td>
<td>3.2</td>
</tr>
</tbody>
</table>
<p>그리고 테스트 전과 후에 필요한 행동이 있다면 TestCase 클래스의 <code>setUp()</code> <code>tearDown()</code> Functions를 활용할 수도 있다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">TestArray</span><span class="params">(unittest.TestCase)</span>:</span></span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Create class instance</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">setUp</span><span class="params">(self)</span>:</span></span><br><span class="line">        self.array = array.Array(<span class="string">'1 2 3 4 10 11'</span>)</span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Test that the result sum of all numbers</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">test_sum</span><span class="params">(self)</span>:</span></span><br><span class="line">        result = self.array.sum(<span class="number">6</span>)</span><br><span class="line">        self.assertEqual(result, <span class="number">31</span>)</span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Tests that an exception occurs when the number of arguments is different</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">test_sum_raise_exception</span><span class="params">(self)</span>:</span></span><br><span class="line">        self.assertRaises(Exception, <span class="keyword">lambda</span>: self.array.sum(<span class="number">5</span>))</span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Print array elements</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">tearDown</span><span class="params">(self)</span>:</span></span><br><span class="line">        print(<span class="string">'elements = &#123;&#125;'</span>.format(self.array))</span><br></pre></td></tr></table></figure>
<p><br></p>
<p><code>TestCase</code>는 <code>unittest.main()</code>이 동작하는 과정에서 자동으로 수집해 실행하지만 아래와 같이 사용자가 원하는 TestCase를 정의해 실행할 수도 있다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">suite</span><span class="params">()</span>:</span></span><br><span class="line">    suite = unittest.TestSuite()</span><br><span class="line">    suite.addTest(TestArray())</span><br><span class="line">    suite.addTest(TestHttp())</span><br><span class="line">    <span class="keyword">return</span> suite</span><br></pre></td></tr></table></figure>
<p><br></p>
<p>마지막으로 우리가 지금까지 살펴 본 <code>unittest</code>를 통한 테스트의 전체적인 흐름을 표현하면 아래와 같다.</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">test</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">for</span> test_case <span class="keyword">in</span> test_suite:</span><br><span class="line">        <span class="keyword">for</span> test_method <span class="keyword">in</span> test_case.test_methods:</span><br><span class="line">            <span class="keyword">try</span>:</span><br><span class="line">                test_case.setUp()</span><br><span class="line">            <span class="keyword">except</span>:</span><br><span class="line">                ..예외를 기록한다</span><br><span class="line">            <span class="keyword">else</span>:</span><br><span class="line">                <span class="keyword">try</span>:</span><br><span class="line">                    test_method()</span><br><span class="line">                <span class="keyword">except</span> AssertionError:</span><br><span class="line">                    ..실패 케이스를 기록한다</span><br><span class="line">                <span class="keyword">except</span>:</span><br><span class="line">                    ..예외를 기록한다</span><br><span class="line">                <span class="keyword">else</span>:</span><br><span class="line">                    ..성공 케이스를 기록한다</span><br><span class="line">                <span class="keyword">finally</span>:</span><br><span class="line">                    <span class="keyword">try</span>:</span><br><span class="line">                        test_case.tearDown()</span><br><span class="line">                    <span class="keyword">except</span>:</span><br><span class="line">                        ..예외를 기록한다</span><br><span class="line">print(test())</span><br></pre></td></tr></table></figure>
<p><br></p>
<p>지금까지 테스트 코드를 먼저 작성하는 것으로 파이썬에 적응해 나아가는 모습을 살펴보았다. 모든 내용을 정리하지는 못했지만 이 과정에서 파이썬의 Built-in Keyword 부터 Function, Classes, Variables를 표현하는 연습도 저절로 할 수 있었다.</p>
<p>파이썬을 A부터 Z까지 학습한 뒤 프로젝트에 활용할 수도 있겠지만 TDD를 통해 다양한 문제에 노출되면서 주도적으로 학습에 필요한 내용을 찾아보았다. 예제는 단순했지만 앞으로 우리가 작성하는 코드는 점점 복잡해지며 나중에는 <code>레거시</code>라는 괴물로 변하기도 한다.</p>
<p>TDD를 통해 지속적으로 변경이 용이한 코드를 작성하는 것을 기대하면서 이 글을 마무리한다. 다음 글에서는 파이썬 프로젝트의 구조와 파이썬의 실행 환경을 지탱하는 다양한 도구들을 살펴보도록 하겠다.</p>
<blockquote>
<p><a href="https://www.holaxprogramming.com/2017/06/28/python-project-structures/">https://www.holaxprogramming.com/2017/06/28/python-project-structures/</a></p>
</blockquote>
<h4 id="References"><a href="#References" class="headerlink" title="References"></a>References</h4><blockquote>
<p><a href="https://docs.python.org/3/library/unittest.html" target="_blank" rel="external">https://docs.python.org/3/library/unittest.html</a><br><a href="https://docs.python.org/3/tutorial/errors.html" target="_blank" rel="external">https://docs.python.org/3/tutorial/errors.html</a></p>
</blockquote>
</div></article></div></main><footer><div class="paginator"><a class="prev" href="/2017/06/15/python-get-started/"><i class="fa fa-arrow-left" aria-hidden="true"></i></a><a class="next" href="/2017/06/28/python-project-structures/"><i class="fa fa-arrow-right" aria-hidden="true"></i></a></div><ins class="adsbygoogle adsense-bottom" style="display:block;" data-ad-client="ca-pub-6188640546219653" data-ad-slot="6129396565" data-ad-format="auto"></ins><div class="fb-comments-area"><div class="fb-comments" data-href="https://www.holaxprogramming.com/2017/06/17/python-with-test/" data-width="700" data-numposts="5"></div></div><div class="copyright"><p>© 2012 - 2022 <a href="https://github.com/stunstunstun" target="_blank">Minhyeok Jung</a>. Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> and <a href="https://github.com/stunstunstun/hexo-theme-chiangmai" target="_blank">hexo-theme-chiangmai</a>.</p></div></footer></div><script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle = window.adsbygoogle || []).push({});</script><script>window.fbAsyncInit=function(){FB.init({appId:"1258629384258634",cookie:!0,xfbml:!0,version:"v2.8"}),FB.AppEvents.logPageView()},function(e,n,t){var o,c=e.getElementsByTagName(n)[0];e.getElementById(t)||((o=e.createElement(n)).id=t,o.src="//connect.facebook.net/en_US/sdk.js",c.parentNode.insertBefore(o,c))}(document,"script","facebook-jssdk");</script><script>(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;e=o.createElement(i);r=o.getElementsByTagName(i)[0];e.src='//www.google-analytics.com/analytics.js';r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));ga('create','UA-97419941-1','auto');ga('send','pageview');</script></body></html>